# Thresholds for code complexity
too-many-arguments-threshold = 7
type-complexity-threshold = 250
enum-variant-size-threshold = 150
cognitive-complexity-threshold = 20

# Size thresholds
array-size-threshold = 8
large-error-threshold = 100
verbose-bit-mask-threshold = 1

# Nesting and lines
excessive-nesting-threshold = 6
too-many-lines-threshold = 200

# Documentation and private items
check-private-items = true
missing-docs-in-crate-items = true