edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
match_block_trailing_comma = false
use_field_init_shorthand = false
use_try_shorthand = false
chain_width = 60
merge_derives = true
